### ISSUE TITLE
Feature request: Store more than one block to a Design

### ISSUE THREAD

**Issue by Jadziyah** [ChiselsAndBits/FlatColoredBlocks#37] opened 2017-02-28 00:23 UTC
Apologies if this has been discussed before; I did look in the FAQ and through the open issues here.

My friends and I were discussing how we'd *love* to be able to store a full build to one Design (positive or negative) paper. Currently if you have a build that is say, only 2x2 in size that's 8 Designs you have to store right off the bat. If you want to recreate it later you need to remember what order they were in, what rotation, etc. It can get real confusing, especially if you want to share your Designs with others. It would be *immensely* helpful if we were able to get a multiblock selection of our entire build on one Design paper. 

Not sure if this is at all possible but wanted to put the idea out there! As always thanks for your great work on these mods!

**Comment by AlgorithmX2** [comment] 2017-02-28 01:16
I believe that this is a duplicate of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/212

Also this is the wrong mod.

**Closed as completed** 2017-03-20 18:50 UTC
Labels: duplicate, invalid
