### ISSUE TITLE
Item to find closest shade

### ISSUE THREAD

**Issue by Richhobo1216** [ChiselsAndBits/FlatColoredBlocks#40] opened 2017-05-01 22:46 UTC
I would like an item that you can use to find the closest shade to what you want. What I mean by this is that you input an RGB or hexadecimal value, and the item finds the shade that matches your input the most out of the shades available.

**Comment by AlgorithmX2** [comment] 2017-05-01 22:50
Basically this is a duplicate of https://github.com/AlgorithmX2/FlatColoredBlocks/issues/10

**Closed as completed by AlgorithmX2** 2017-05-01 22:50 UTC
Labels: duplicate

**Comment by Richhobo1216** [comment] 2017-05-02 04:59
Oh ok you just changed the title of it. I created a new one because #10 was different when I made it.

**Comment by AlgorithmX2** [comment] 2017-05-02 05:01
Yeah, the description has evolved over time, so It really needed to be updated. It wasn't obvious that this was a duplicate unless you read over the details on that one.
